package fr.mrqsdf.bossrush.res;

public enum DisplayState {

    ATTACK,
    DEFEND,
    INVENTORY,
    ITEM,
    USABLE,
    GAME_OVER,
    MOVE,
    PLAYER_HEAL_HUD_FULL,
    PLAYER_HEAL_HUD_EMPTY,
    PLAYER_MANA_HUD_FULL,
    PLAYER_MANA_HUD_EMPTY,
    PLAYER_EXP_HUD_FULL,
    PLAYER_EXP_HUD_EMPTY,
    MOB_HEAL_HUD_FULL,
    MOB_HEAL_HUD_EMPTY,
    MOB_MANA_HUD_FULL,
    MOB_MANA_HUD_EMPTY;

}
